[workspace]
members = ["core", "cli", "gui"]
resolver = "2"

[workspace.package]
version = "0.1.8"
edition = "2021"
authors = ["Franz Geffke <mail@gofranz.com>"]
license = "MIT"
repository = "https://github.com/franzos/iota-wallet"
description = "Monero-inspired wallet for IOTA Rebased"
